language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U https://github.com/platformio/platformio/archive/develop.zip

script:
    - platformio test -e local | tail -n 1 | grep PASSED
