language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio lib -g install 13 81 978

script:
    - platformio ci --board="leonardo" src --lib="./lib/Follower" --lib="./lib/Menu"  --lib="./lib/Storage"
