language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=src/main.cpp PLATFORMIO_BUILD_FLAGS="-Ldir lib/Menu -I lib/Menu"
  - PLATFORMIO_CI_SRC=test/run.cpp

install:
    - pip install -U platformio
    - platformio lib -g install 13 81 978

script:
    - platformio ci --board=leonardo
