language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install twisted platformio==3.1.0 

script:
    - platformio --version
    - platformio test -e local | tail -n 1 | grep PASSED
