language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=src/main.cpp
  - PLATFORMIO_CI_SRC=test/

install:
    - pip install -U platformio
    - platformio lib -g install 13
    - platformio lib -g install 81
    - platformio lib -g install 978

script:
    - platformio ci --board=leonardo
